baseURL: https://www.blog.galligan.dev
languageCode: en-ie
enableInlineShortcodes: true
title: "Gal's Blog"
theme: PaperMod
defaultTheme: light
disableThemeToggle: true
markup:
  goldmark:
    renderer:
      unsafe: true
Params:
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowCopyCodeButtons: true